---
# TODO comments

- name: Read timezone
  slurp:
    src: "/etc/timezone"
  register: timezone_encoded

- name: Decode timezone
  set_fact:
    timezone: "{{ timezone_encoded.content | b64decode }}"

- name: Create configuration directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
  loop:
    - "{{ dns_server_path }}"
    - "{{ dns_server_path }}/stubby"
    - "{{ dns_server_path }}/pihole"
    # - "{{ dns_server_path }}/pihole/etc-pihole"
    # - "{{ dns_server_path }}/pihole/etc-dnsmasq.d"

# Stubby image configuration
- name: "[Stubby] Setup docker runtime"
  template:
    src: "stubby/{{ item }}"
    dest: "{{ dns_server_path }}/stubby/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'
  loop:
    - Dockerfile
    - entrypoint.sh
  notify: restart docker dns-server

- name: "[Stubby] Copy configuration file"
  template:
    src: stubby/stubby.yml
    dest: "{{ dns_server_path }}/stubby/stubby.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'

# Application docker configuration
- name: Setup docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ dns_server_path }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'
  notify: restart docker dns-server

- name: UFW - Allow connections
  ufw:
    rule: allow
    port: "53"
    src: '{{ item }}'
  with_items:
    - "{{ dns_server_listening }}"
  become: true

# Disable host DNS resolver to free the port 53 and allow the container to use it
- name: Disable stub resolver
  block:
    - name: Disable the stub resolver [1/4]
      lineinfile:
        path: /etc/systemd/resolved.conf
        search_string: 'DNSStubListener=yes'
        line: 'DNSStubListener=no'
      register: stub_resolver

    - name: Disable the stub resolver [2/4 - Remove /etc/resolv.conf]
      file:
        path: /etc/resolv.conf
        state: absent
      when: stub_resolver.changed

    - name: Disable the stub resolver [3/4 - Replace /etc/resolv.conf with symlink]
      file:
        path: /etc/resolv.conf
        src: /run/systemd/resolve/resolv.conf
        state: link
      when: stub_resolver.changed

    - name: Disable the stub resolver [4/4 - restart resolved]
      service:
        name: systemd-resolved
        state: restarted
      when: stub_resolver.changed
  become: true

- name: Flush handlers
  meta: flush_handlers

- name: Ensure the dns server is running
  community.docker.docker_compose:
    project_src: "{{ dns_server_path }}"
    build: yes
  become: true
