---
# Read system timezone and set it as a fact
# to propagate it to the containers.
- name: Read timezone
  ansible.builtin.slurp:
    src: "/etc/timezone"
  register: timezone_encoded

- name: Decode timezone
  ansible.builtin.set_fact:
    timezone: "{{ timezone_encoded.content | b64decode }}"

# Create the directory tree
- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
  loop:
    - "{{ dns_server_path }}"
    - "{{ dns_server_path }}/stubby"
    - "{{ dns_server_path }}/pihole"

# Stubby image configuration
- name: "[Stubby] Setup docker runtime"
  ansible.builtin.template:
    src: "stubby/{{ item }}"
    dest: "{{ dns_server_path }}/stubby/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'
  loop:
    - Dockerfile
    - entrypoint.sh
  notify: Restart docker dns-server
  when: stubby_enabled

- name: "[Stubby] Copy configuration file"
  ansible.builtin.template:
    src: stubby/stubby.yml
    dest: "{{ dns_server_path }}/stubby/stubby.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'
  when: stubby_enabled

# DNS Server docker-compose configuration
- name: Setup docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ dns_server_path }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'
  notify: Restart docker dns-server

# Allow traffic on the default DNS server port
- name: UFW - Allow connections to the DNS server
  community.general.ufw:
    rule: allow
    port: "53"
    src: '{{ item }}'
  with_items:
    - "{{ dns_server_listening }}"
  become: true

- name: UFW - Allow connections to the pihole web interface
  community.general.ufw:
    rule: allow
    port: "{{ pihole_http_port }}"
    src: '{{ item }}'
  with_items:
    - "{{ dns_server_listening }}"
  when: pihole_enabled and not (traefik is defined and traefik)
  become: true

# Disable host DNS resolver to free the port 53 and allow the container to use it
- name: Disable stub resolver
  become: true
  block:
    - name: Disable the stub resolver [1/4]
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        search_string: 'DNSStubListener=yes'
        line: 'DNSStubListener=no'
      register: stub_resolver

    - name: Disable the stub resolver [2/4 - Remove /etc/resolv.conf]
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
      when: stub_resolver.changed

    - name: Disable the stub resolver [3/4 - Replace /etc/resolv.conf with symlink]
      ansible.builtin.file:
        path: /etc/resolv.conf
        src: /run/systemd/resolve/resolv.conf
        state: link
      when: stub_resolver.changed

    - name: Disable the stub resolver [4/4 - restart resolved]
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
      when: stub_resolver.changed

# Execute all the actions of the handlers that have been notified.
# It allows the container to restart or build itself before ensuring that
# it is actually running. We need to ensure it is running in case you
# run the task after nothing has been changed by the container was stopped.
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure the dns server is running
  community.docker.docker_compose:
    project_src: "{{ dns_server_path }}"
    build: yes
  become: true
